title: 정리하는 블로그
description: 기록쌓기

remote_theme: pages-themes/cayman@v0.2.0
url: "https://funetes.github.io"
baseurl: ""
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-remote-theme

paginate: 10
paginate_path: "/page:num/"
